Internal Server Error: /api/design/271/attachments/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\views.py", line 446, in get
    attachments["other"]["links"].insert(
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: list indices must be integers or slices, not str
"GET /api/design/271/attachments/ HTTP/1.1" 500 112424
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2453
Not Found: /admin/log-view/
"GET /admin/log-view/ HTTP/1.1" 404 6161
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2338
Internal Server Error: /api/supervision/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'
"GET /api/supervision/ HTTP/1.1" 500 130171
