Internal Server Error: /api/design/271/attachments/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\views.py", line 446, in get
    attachments["other"]["links"].insert(
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: list indices must be integers or slices, not str
"GET /api/design/271/attachments/ HTTP/1.1" 500 112424
You're accessing the development server over HTTPS, but it only supports HTTP.
You're accessing the development server over HTTPS, but it only supports HTTP.
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2453
Not Found: /admin/log-view/
"GET /admin/log-view/ HTTP/1.1" 404 6161
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2338
Internal Server Error: /api/supervision/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 795, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 249, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 714, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 523, in to_representation
    for field in fields:
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 384, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'
"GET /api/supervision/ HTTP/1.1" 500 130171
Unauthorized: /api/visits/
"GET /api/visits/ HTTP/1.1" 401 58
Internal Server Error: /api/visits/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 173, in create
    raise NotImplementedError('`create()` must be implemented.')
NotImplementedError: `create()` must be implemented.
"POST /api/visits/ HTTP/1.1" 500 112686
Bad Request: /api/visits/
"POST /api/visits/ HTTP/1.1" 400 117
Bad Request: /api/visits/
"POST /api/visits/ HTTP/1.1" 400 40
Bad Request: /api/visits/
"POST /api/visits/ HTTP/1.1" 400 40
Bad Request: /api/visits/
"POST /api/visits/ HTTP/1.1" 400 40
Internal Server Error: /api/visits/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\views.py", line 323, in create
    return super().create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 663, in create
    return super().create(validated_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 284, in __set__
    raise ValueError(
ValueError: Cannot assign "<django.contrib.auth.models.AnonymousUser object at 0x00000146E4749D90>": "Visit.employee" must be a "Employee" instance.
"POST /api/visits/ HTTP/1.1" 500 148158
Internal Server Error: /api/visits/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: Visit() got unexpected keyword arguments: 'written_by'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\views.py", line 323, in create
    return super().create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 667, in create
    return super().create(validated_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 1008, in create
    raise TypeError(msg)
TypeError: Got a `TypeError` when calling `Visit.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `Visit.objects.create()`. You may need to make the field read-only, or override the VisitSerializer.create() method to handle this correctly.
Original exception was:
 Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: Visit() got unexpected keyword arguments: 'written_by'

"POST /api/visits/ HTTP/1.1" 500 166357
Internal Server Error: /api/visits/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NotNullViolation: null value in column "employee_id" of relation "api_visit" violates not-null constraint
DETAIL:  Failing row contains (2, 2024-01-02, null, null, , null, 1).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\views.py", line 323, in create
    return super().create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 667, in create
    return super().create(validated_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 989, in create
    instance = ModelClass._default_manager.create(**validated_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: null value in column "employee_id" of relation "api_visit" violates not-null constraint
DETAIL:  Failing row contains (2, 2024-01-02, null, null, , null, 1).

"POST /api/visits/ HTTP/1.1" 500 210724
Unauthorized: /api/visits/
"GET /api/visits/ HTTP/1.1" 401 58
Unauthorized: /api/visits/
"GET /api/visits/ HTTP/1.1" 401 58
Unauthorized: /api/visits/
"GET /api/visits/ HTTP/1.1" 401 58
Bad Request: /api/reception/
"POST /api/reception/ HTTP/1.1" 400 87
Internal Server Error: /api/reception/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 145, in create
    History.objects.create(
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 284, in __set__
    raise ValueError(
ValueError: Cannot assign "<ReceptionProject: ReceptionProject object (45)>": "History.project" must be a "GlobalID" instance.
"POST /api/reception/ HTTP/1.1" 500 136713
Bad Request: /api/history/
"GET /api/history/?project=588 HTTP/1.1" 400 87
Internal Server Error: /api/reception/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 142, in create
    global_id = GlobalIDSerializer.create()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: GlobalIDSerializer.create() missing 2 required positional arguments: 'self' and 'validated_data'
"POST /api/reception/ HTTP/1.1" 500 116928
Internal Server Error: /api/reception/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 142, in create
    global_id = GlobalIDSerializer.create(self, {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 705, in create
    return super().create(validated_data)
           ^^^^^^^^^^^^^^
TypeError: super(type, obj): obj must be an instance or subtype of type
"POST /api/reception/ HTTP/1.1" 500 121233
Internal Server Error: /api/reception/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 143, in create
    result.global_id = global_id
    ^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 284, in __set__
    raise ValueError(
ValueError: Cannot assign "{'id': 588, 'design': None, 'balady': None, 'sorting': None, 'land': None, 'qatari': None, 'supervision': None}": "ReceptionProject.global_id" must be a "GlobalID" instance.
"POST /api/reception/ HTTP/1.1" 500 122856
Internal Server Error: /api/reception/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 143, in create
    global_id = global_id_serializer.save()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 176, in save
    assert hasattr(self, '_errors'), (
AssertionError: You must call `.is_valid()` before calling `.save()`.
"POST /api/reception/ HTTP/1.1" 500 123087
Internal Server Error: /api/reception/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 143, in create
    global_id_serializer.is_valid(raise_exception=True)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 216, in is_valid
    assert hasattr(self, 'initial_data'), (
AssertionError: Cannot call `.is_valid()` as no `data=` keyword argument was passed when instantiating the serializer instance.
"POST /api/reception/ HTTP/1.1" 500 123523
Bad Request: /api/reception/
"POST /api/reception/ HTTP/1.1" 400 79
Internal Server Error: /api/reception/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 143, in create
    global_id = global_id_serializer.save()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 699, in create
    user=self.context["request"].user,
         ~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'request'
"POST /api/reception/ HTTP/1.1" 500 128205
Internal Server Error: /api/reception/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 143, in create
    global_id = global_id_serializer.save()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 700, in create
    user=self.context["request"].user,
         ~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'request'
"POST /api/reception/ HTTP/1.1" 500 128440
Internal Server Error: /api/reception/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 143, in create
    global_id = global_id_serializer.save()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 704, in create
    ip=self.context["request"].META.get("REMOTE_ADDR"),
       ~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'request'
"POST /api/reception/ HTTP/1.1" 500 128387
Internal Server Error: /api/reception/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NotNullViolation: null value in column "user_id" of relation "api_history" violates not-null constraint
DETAIL:  Failing row contains (2, created, null, reception.reception, 2024-09-13 08:23:04.260426+03, null, 609, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 143, in create
    global_id = global_id_serializer.save()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 699, in create
    History.objects.create(
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: null value in column "user_id" of relation "api_history" violates not-null constraint
DETAIL:  Failing row contains (2, created, null, reception.reception, 2024-09-13 08:23:04.260426+03, null, 609, null).

"POST /api/reception/ HTTP/1.1" 500 212793
Internal Server Error: /api/reception/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 143, in create
    global_id = global_id_serializer.save()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 699, in create
    History.objects.create(
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 284, in __set__
    raise ValueError(
ValueError: Cannot assign "1": "History.user" must be a "Employee" instance.
"POST /api/reception/ HTTP/1.1" 500 147955
Internal Server Error: /api/reception/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 143, in create
    global_id = global_id_serializer.save()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 209, in save
    assert self.instance is not None, (
AssertionError: `create()` did not return an object instance.
"POST /api/reception/ HTTP/1.1" 500 123255
Internal Server Error: /api/reception/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\serializers.py", line 147, in create
    History.objects.create(
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\query.py", line 677, in create
    obj = self.model(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\base.py", line 543, in __init__
    _setattr(self, field.name, rel_obj)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 284, in __set__
    raise ValueError(
ValueError: Cannot assign "<ReceptionProject: ReceptionProject object (69)>": "History.project" must be a "GlobalID" instance.
"POST /api/reception/ HTTP/1.1" 500 138430
Internal Server Error: /api/reception/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\mixins.py", line 9, in create
    global_id_serializer.is_valid(raise_exception=True)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 216, in is_valid
    assert hasattr(self, 'initial_data'), (
AssertionError: Cannot call `.is_valid()` as no `data=` keyword argument was passed when instantiating the serializer instance.
"POST /api/reception/ HTTP/1.1" 500 123464
Internal Server Error: /api/reception/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 209, in save
    assert self.instance is not None, (
AssertionError: `create()` did not return an object instance.
"POST /api/reception/ HTTP/1.1" 500 111367
Internal Server Error: /api/reception/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\mixins.py", line 7, in create
    print(self.context.request)
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'request'
"POST /api/reception/ HTTP/1.1" 500 116013
Bad Request: /api/design/1/
"PUT /api/design/1/ HTTP/1.1" 400 55
Not Found: /api/deleted/
"GET /api/deleted/ HTTP/1.1" 404 19308
Internal Server Error: /api/deleted_projects/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\views.py", line 757, in get
    deleted_projects = design_projects + balady_projects + land_projects + sort_projects + qatari_projects + supervision_projects
                       ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'QuerySet' and 'QuerySet'
"GET /api/deleted_projects/ HTTP/1.1" 500 101212
Internal Server Error: /api/reception/
Traceback (most recent call last):
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\venv\Lib\site-packages\rest_framework\serializers.py", line 208, in save
    self.instance = self.create(validated_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ad-10\WebDev\Aljarrash\aljarrash-backend\api\mixins.py", line 7, in create
    print(self.context["request"].META.PATH_INFO)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'PATH_INFO'
"POST /api/reception/ HTTP/1.1" 500 116117
Bad Request: /api/supervision/
"POST /api/supervision/ HTTP/1.1" 400 123
